#!/usr/bin/env bash
# Regenerate docs-site/src/reference/cli.md from the real `--help` output of
# the built mcptracer binary, so the published reference can never drift from
# what the CLI actually accepts. This is the full flag dump; for a one-line-
# per-command "what is this for" map, see capabilities.md, generated by
# generate-capability-reference.sh.
#
# Usage: scripts/generate-cli-reference.sh
set -euo pipefail
cd "$(dirname "$0")/.."

cargo build -q --bin mcptracer
BIN="target/debug/mcptracer"
[ -x "$BIN" ] || BIN="target/debug/mcptracer.exe"
[ -x "$BIN" ] || {
    echo "error: could not find the built mcptracer binary" >&2
    exit 1
}

# One level of subcommands; commands with their own nested subcommand (e.g.
# `sessions list|show|export-otel`) still get a top-level --help entry here.
COMMANDS=(
    record record-http setup replay replay-http serve validate merge sessions diff
    diff-batch eval assert baseline bench stats search export import verify
    index route optimize graph inspect
)
if "$BIN" --help | grep -q '^  semantic '; then
    COMMANDS+=(semantic)
fi

OUT="docs-site/src/reference/cli.md"
{
    echo "# CLI Commands"
    echo
    echo "Generated from \`mcptracer --help\` and each subcommand's \`--help\`. Do not"
    echo "hand-edit; regenerate with \`scripts/generate-cli-reference.sh\`."
    echo
    echo '```text'
    "$BIN" --help
    echo '```'
    echo
    for cmd in "${COMMANDS[@]}"; do
        echo "## \`mcptracer ${cmd}\`"
        echo
        echo '```text'
        "$BIN" "$cmd" --help
        echo '```'
        echo
    done
} | sed -e 's/mcptracer\.exe/mcptracer/g' -e 's/[[:space:]]\+$//' > "$OUT"

echo "wrote $OUT"
