#!/usr/bin/env bash
# Regenerate docs-site/src/reference/capabilities.md -- the one-page "what
# does this actually do" map (T-88) -- from the real `mcptracer --help`
# output, so the published capability list can never claim a command that
# doesn't exist or omit one that does. Each command's one-line description is
# taken verbatim from its own top-level --help, not hand-copied. Grouping
# into job categories (capture/reproduce/compare/gate/share/derive/team) is
# necessarily editorial and lives in this script's command_group function;
# a command --help lists that isn't classified fails the build loudly instead
# of silently being left off the page -- the exact "shipped, written down
# nowhere" failure mode T-88 exists to close (see backlog.md T-88).
#
# For the flag-level detail on any one command, see cli.md, generated by
# generate-cli-reference.sh.
#
# Usage: scripts/generate-capability-reference.sh
set -euo pipefail
cd "$(dirname "$0")/.."

cargo build -q --bin mcptracer --all-features
BIN="target/debug/mcptracer"
[ -x "$BIN" ] || BIN="target/debug/mcptracer.exe"
[ -x "$BIN" ] || {
    echo "error: could not find the built mcptracer binary" >&2
    exit 1
}

OUT="docs-site/src/reference/capabilities.md"
GROUP_ORDER=(capture reproduce compare gate share derive)

group_title() {
    case "$1" in
        capture) echo "Capture -- get real MCP traffic into the system" ;;
        reproduce) echo "Reproduce -- regenerate traffic from what was captured" ;;
        compare) echo "Compare -- find what changed between two sessions" ;;
        gate) echo "Gate -- pass/fail checks a CI pipeline can act on" ;;
        share) echo "Share -- export, browse, and inspect recorded evidence" ;;
        derive) echo "Derive -- mine recorded history for insight (Labs)" ;;
        *) return 1 ;;
    esac
}

command_group() {
    case "$1" in
        record|record-http|setup|merge) echo capture ;;
        replay|replay-http|serve|bench) echo reproduce ;;
        diff|diff-batch|eval) echo compare ;;
        validate|assert|baseline|verify|quota) echo gate ;;
        export|import|sessions|stats|search|inspect) echo share ;;
        index|route|optimize|graph|semantic) echo derive ;;
        *) return 1 ;;
    esac
}

# command -> extra note appended after its real --help description.
command_note() {
    case "$1" in
        index|route|optimize|graph)
            echo "*(Labs: derived, outside the protocol hot path)*"
            ;;
        semantic) echo "*(Labs)*" ;;
        *) printf '%s' "" ;;
    esac
}

# macOS ships Bash 3.2, which has neither associative arrays nor mapfile.
# Keep the generated source in a temporary file so both loops run in the
# current shell and failures remain visible under `set -e`.
HELP_FILE="$(mktemp)"
trap 'rm -f "$HELP_FILE"' EXIT
"$BIN" --help | sed -n '/^Commands:/,/^Options:/p' | sed '1d;$d' > "$HELP_FILE"

{
    echo "# Capability Reference"
    echo
    echo "What MCPTracer actually does, one line per command, grouped by the job it"
    echo "does. **Generated from \`mcptracer --help\`; do not hand-edit** --"
    echo "regenerate with \`scripts/generate-capability-reference.sh\`. For every flag"
    echo "on every command, see the full [CLI reference](cli.md)."
    echo

    first_job=1
    for job in "${GROUP_ORDER[@]}"; do
        if [ "$first_job" -eq 0 ]; then
            echo
        fi
        first_job=0
        echo "## $(group_title "$job")"
        echo
        while IFS= read -r line; do
            name="$(echo "$line" | awk '{print $1}')"
            [ -z "$name" ] && continue
            [ "$name" = "help" ] && continue
            [ "$(command_group "$name" 2>/dev/null || true)" = "$job" ] || continue
            desc="$(echo "$line" | sed -E 's/^[[:space:]]*[^[:space:]]+[[:space:]]+//')"
            note="$(command_note "$name")"
            if [ -n "$note" ]; then
                echo "- \`mcptracer $name\` -- $desc $note"
            else
                echo "- \`mcptracer $name\` -- $desc"
            fi
        done < "$HELP_FILE"
    done
} > "$OUT"

# Fail loudly on any command --help lists that this script has no grouping
# for, rather than silently dropping it from the page.
missing=0
while IFS= read -r line; do
    name="$(echo "$line" | awk '{print $1}')"
    [ -z "$name" ] && continue
    [ "$name" = "help" ] && continue
    if ! command_group "$name" >/dev/null 2>&1; then
        echo "error: '$name' is not classified in command_group; add it to $0" >&2
        missing=1
    fi
done < "$HELP_FILE"
[ "$missing" -eq 0 ] || exit 1

echo "wrote $OUT"
